### ISSUE TITLE
Again errors when opening Excel files

### ISSUE THREAD

**Issue by chbeer** [charlymr/XlsxReaderWriter#33] opened 2021-09-30 19:56 UTC
There were problems opening Excel files with earlier versions. 

Since I switched to the SPM version I got this error again:

![IMG_2B25AB2011A6-1](https://user-images.githubusercontent.com/121761/135521577-9661ca8c-8cd8-4a88-8a14-64ab3dee4166.jpeg)

Anybody else? In the past it was related to (SS)ZipArchive and/or a missing XML-node. Does somebody else have this?

**Comment by chbeer** [comment] 2021-09-30 20:06
This also happens with the current CocoaPods version. I'm sure it was fixed 🤔

**Comment by shiva-menlo** [comment] 2021-11-24 07:49
Any solution for this? Even i am getting this error.
<img width="257" alt="Screenshot 2021-11-24 at 1 18 18 PM" src="https://user-images.githubusercontent.com/17330421/143196446-3d9f4ee2-ab88-4a4a-b680-5da657709422.png">
.

**Comment by chbeer** [comment] 2021-11-24 07:56
As far as I understand, the problem is coming from ZipArchive creating some kind of wrong ZIP. I „solved“ this issue by using an older version of ZipArchive.

**Comment by shiva-menlo** [comment] 2021-11-24 07:59
Can you please let us know which ZipArchive version did you used?

**Comment by chbeer** [comment] 2021-11-24 08:13
Sure, I cloned XlsxReaderWriter to change the dependency:
https://github.com/chbeer/XlsxReaderWriter.git / master branch

**Comment by shiva-menlo** [comment] 2021-11-24 08:26
@chbeer , thank you for git url. I will update to this later.
as a hot fix I just changed below line in my pod file,  i know it's going backwards but fixed for now.

  pod 'SSZipArchive', '2.2'
  pod 'XlsxReaderWriter', '2.4.1', :source => 'https://github.com/charlymr/XlsxReaderWriter-Podspecs.git''

**Comment by chbeer** [comment] 2021-11-24 08:43
Yes, I did something like that as well. But we switched to SPM and that's not as easy to fix there.

**Comment by shiva-menlo** [comment] 2021-11-24 08:46
OK @chbeer ,
Thank you for helping me out on this (Y)

**Comment by charlymr** [comment] 2021-11-24 20:33
@chbeer @shiva-menlo I am trying to use an older version of ZipArchive. with 2.3.0 the Xlsx file open fine without error. Will try to push the update tomorrow.

**Comment by charlymr** [comment] 2021-11-25 11:28
@chbeer @shiva-menlo the issue is fixed with version 2.5.0. https://github.com/charlymr/XlsxReaderWriter/releases/tag/2.5.0

The lib is no longer dependent of ZipArchive, so you can use it with either SPM, Cocoapods or Carthage.

**Closed as completed by charlymr** 2021-11-25 11:28 UTC
Labels: bug
